openapi: 3.0.1
info:
  title: URL Shortener API
  description: API for creating and retrieving shortened URLs
  version: '1.0.0'
servers:
  - url: http://localhost:3000
paths:
  /api/urls:
    post:
      summary: Create a shortened URL
      description: Creates a new shortened URL for the provided original URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                original_url:
                  type: string
                  description: The original URL to shorten
                  example: https://example.com
      responses:
        '201':
          description: Shortened URL created
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    description: The generated shortened URL
                    example: http://localhost:3000/abc123
                  original_url:
                    type: string
                    description: The original URL
                    example: https://example.com
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: ["Original URL can't be blank"]
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
components:
  securitySchemes:
    ApiTokenAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiTokenAuth: []
